name: Publish Package mangrove.js
on: 
  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - minor
        - major
        - patch
jobs:
  publish-mangrove-js:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Infos
      run: |
        echo "revision: $INPUT_REVISION"
      env:
        INPUT_REVISION: ${{ inputs.revision }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Node Install
      uses: actions/setup-node@v3
      with:
        node-version: v16.20.0

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    
    - name: Yarn install
      run: |
        node --version
        yarn --version
        yarn install --immutable

    - name: Bump version
      run: |
        echo $INPUT_REVISION
        npm version --no-git-tag-version $INPUT_REVISION 2>/dev/null || true
      working-directory: packages/mangrove.js
      env:
        INPUT_REVISION: ${{ inputs.revision }}

    # - name: Publish
    #   run: |
    #     if [ "$INPUT_REVISION" = "prerelease" ]; then
    #       tag="next"
    #     else
    #       tag="latest"
    #     fi
    #
    #     echo "npmAuthToken: \"$NPM_TOKEN\"" >> .yarnrc.yml
    #     cd packages/mangrove.js
    #     yarn npm publish --access public --tag $tag
    #   env:
    #     INPUT_REVISION: ${{ inputs.revision }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - name: setup git
    #   run: |
    #     echo "INPUT_COMMIT_USER_NAME: ${INPUT_COMMIT_USER_NAME}";
    #     git config --global user.name  "${INPUT_COMMIT_USER_NAME}";
    #     echo "INPUT_COMMIT_USER_EMAIL: ${INPUT_COMMIT_USER_EMAIL}";
    #     git config --global user.email ${INPUT_COMMIT_USER_EMAIL}
    #
    #   env:
    #     INPUT_COMMIT_USER_NAME:  github-actions-bot
    #     INPUT_COMMIT_USER_EMAIL: automation@mangrove.exchange

    - name: git version
      run: |
        git status
        PACKAGE_VERSION=$(cat package.json \
        | grep version \
        | head -1 \
        | awk -F: '{ print $2 }' \
        | sed 's/[",]//g' | cut -c2- )
        echo "version: $PACKAGE_VERSION"
        git switch -c "release/v$PACKAGE_VERSION"
        git add package.json 
        git commit -S -m "$PACKAGE_VERSION [$USER]"
        # git tag -m "v$PACKAGE_VERSION" -s "v$PACKAGE_VERSION"
        git push --set-upstream origin release/v$PACKAGE_VERSION
        # git push --tags
        export RELEASE_NOTES=`sed -n "/^# $PACKAGE_VERSION/,/^#/p" CHANGELOG.md | grep -v "^#" | sed -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba'`
        echo $RELEASE_NOTES
        # gh release create "v$PACKAGE_VERSION" --title "v$PACKAGE_VERSION" --notes "$RELEASE_NOTES"
        gh pr create --title "v$PACKAGE_VERSION" --body "$RELEASE_NOTES" --reviewer "mangrovedao/all-devs"
        gh pr merge --squash --delete-branch --auto
      working-directory: packages/mangrove.js
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        USER: ${{ github.actor }}
