name: Check and update deployment addresses in mangrove.js

# run on master to detect and create PR's to fix any discrepancy between deployment addresses for
# core contracts in mangrove-solidity and mangrove.js

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm ci
        working-directory: ./.github/scripts

      - name: Check and update deployment addresses in mangrove.js
        run: npx ts-node write-addresses-json --deployment $GITHUB_WORKSPACE/packages/mangrove-solidity/deployments/mumbai --chainkey maticmum --output $GITHUB_WORKSPACE/packages/mangrove.js/src/constants/addresses.json --debug
        working-directory: ./.github/scripts/src

      - name: Run prettier on addresses.json
        run: npx prettier --write src/constants/addresses.json
        working-directory: ./packages/mangrove.js

      - name: Create commit and PR, if there are changes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'Update deployment addresses in mangrove.js'
          title: 'Update deployment addresses in mangrove.js'
          body: 'Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action as a result of changes in ${{ github.sha }}.'
          add-paths: 'packages/mangrove.js/src/constants/addresses.json'
          delete-branch: true
          assignees: 'dontrolle'
          labels: automated pr

      - name: Create repository dispatch for mangrove-docs address update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_PUBLIC_ACCESS_TOKEN }}
          repository: mangrovedao/mangrove-docs
          event-type: update-addresses

      # Use this step instead, to simply commit and push changes directly to master
      # - name: Commit and push any changes to deployment addresses
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: 'Update deployment addresses in mangrove.js'
      #     push: true 
      #     add: 'packages/mangrove.js/src/constants/addresses.json'
